"""
SQLAlchemy ORM models for reconciliation service
"""
from datetime import datetime
from decimal import Decimal
from sqlalchemy import (
    Column, Integer, String, DateTime, Numeric, ForeignKey, 
    UniqueConstraint, Index, Text, Enum as SQLEnum, JSON
)
from sqlalchemy.orm import relationship
import enum
from database import Base


class BankTransaction(Base):
    """Bank transaction records"""
    __tablename__ = "bank_transactions"
    
    id = Column(Integer, primary_key=True, index=True)
    txn_id = Column(String(100), unique=True, index=True, nullable=False)
    txn_date = Column(DateTime, index=True, nullable=False)
    account_iban = Column(String(34), nullable=False)
    counterparty_name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    amount = Column(Numeric(18, 4), nullable=False)  # Can be positive or negative
    currency = Column(String(3), nullable=False, index=True)
    bank_reference = Column(String(255), nullable=False)
    import_batch_id = Column(String(100), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    reconciliation_entries = relationship("ReconciliationEntry", back_populates="bank_transaction")
    suggestions = relationship("ReconciliationSuggestion", back_populates="bank_transaction", foreign_keys="ReconciliationSuggestion.txn_id")
    
    __table_args__ = (
        Index("idx_txn_date_currency", "txn_date", "currency"),
    )


class Invoice(Base):
    """Accounts receivable invoices"""
    __tablename__ = "invoices"
    
    id = Column(Integer, primary_key=True, index=True)
    invoice_id = Column(String(100), unique=True, index=True, nullable=False)
    invoice_date = Column(DateTime, index=True, nullable=False)
    due_date = Column(DateTime, nullable=False)
    customer_id = Column(String(100), nullable=False, index=True)
    customer_name = Column(String(255), nullable=False, index=True)
    amount_gross = Column(Numeric(18, 4), nullable=False)
    currency = Column(String(3), nullable=False, index=True)
    status = Column(String(20), nullable=False, index=True)  # open, paid, partially_paid
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    reconciliation_entries = relationship("ReconciliationEntry", back_populates="invoice")
    suggestions = relationship("ReconciliationSuggestion", back_populates="invoice", foreign_keys="ReconciliationSuggestion.invoice_id")
    
    __table_args__ = (
        Index("idx_invoice_date_currency", "invoice_date", "currency"),
    )


class ReconciliationSuggestion(Base):
    """Reconciliation suggestions generated by matching rules"""
    __tablename__ = "reconciliation_suggestions"
    
    id = Column(Integer, primary_key=True, index=True)
    suggestion_key = Column(String(255), unique=True, index=True, nullable=False)  # Hash of (txn_id, invoice_id, rule_version)
    txn_id = Column(String(100), ForeignKey("bank_transactions.txn_id"), nullable=False, index=True)
    invoice_id = Column(String(100), ForeignKey("invoices.invoice_id"), nullable=False, index=True)
    rule_version = Column(String(50), nullable=False)
    confidence = Column(Numeric(5, 2), nullable=False)  # 0.00 to 1.00
    reason = Column(Text, nullable=False)
    status = Column(String(20), nullable=False, index=True)  # pending, approved, rejected
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    bank_transaction = relationship("BankTransaction", back_populates="suggestions", foreign_keys=[txn_id])
    invoice = relationship("Invoice", back_populates="suggestions", foreign_keys=[invoice_id])
    
    __table_args__ = (
        Index("idx_status_created", "status", "created_at"),
    )


class ReconciliationEntry(Base):
    """Booked reconciliation entries (approved matches)"""
    __tablename__ = "reconciliation_entries"
    
    id = Column(Integer, primary_key=True, index=True)
    txn_id = Column(String(100), ForeignKey("bank_transactions.txn_id"), nullable=False, index=True)
    invoice_id = Column(String(100), ForeignKey("invoices.invoice_id"), nullable=False, index=True)
    amount_applied = Column(Numeric(18, 4), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Relationships
    bank_transaction = relationship("BankTransaction", back_populates="reconciliation_entries")
    invoice = relationship("Invoice", back_populates="reconciliation_entries")
    
    __table_args__ = (
        UniqueConstraint("txn_id", "invoice_id", name="uq_txn_invoice"),
    )


class AuditEvent(Base):
    """Append-only audit log for all operations"""
    __tablename__ = "audit_events"
    
    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    actor_type = Column(String(20), nullable=False)  # system, user
    actor_id = Column(String(255), nullable=False, index=True)
    event_type = Column(String(100), nullable=False, index=True)  # import_bank_completed, reconcile_approved, etc.
    entity_type = Column(String(50), nullable=True, index=True)  # BankTransaction, Invoice, etc.
    entity_id = Column(String(255), nullable=True, index=True)
    metadata_json = Column(JSON, nullable=True)  # Additional context
    before_state = Column(JSON, nullable=True)  # Previous state snapshot
    after_state = Column(JSON, nullable=True)  # New state snapshot
    
    __table_args__ = (
        Index("idx_event_type_timestamp", "event_type", "timestamp"),
        Index("idx_entity_timestamp", "entity_type", "entity_id", "timestamp"),
    )
